### ISSUE TITLE
Peer-peer-code review

### ISSUE THREAD

**Issue by jaamanu** [Khaled-AlKhateeb/motor-tech#4]
- All Pages works well 
- Toggle menu works well
- Hover effect needs to be active
- overall margins and alignment looks great

**Comment by Khaled-AlKhateeb** [comment]
Thank you for your review, will work on the hover effects, much appreciated 💯

**Comment by Allenkeys** [comment]
Great job @Khaled-AlKhateeb :fist_raised: 

Quite inspiring!

**Comment by Khaled-AlKhateeb** [comment]
thank you @Allenkeys for your review 👼
